---

- name: Configuring grub
  template:
    src: 'defaults/{{ ansible_facts.os_family }}/grub.j2'
    dest: /etc/default/grub
    mode: '644'
    owner: root
    group: root

- name: Reconfiguring grub
  command:
    cmd: update-grub -o /boot/grub/grub.cfg

