---

- name: Gathering all facts
  include_tasks: 00_facts.yaml

- name: Running generic pre tasks
  include_tasks: shared_pre/main.yaml

- name: Checking if configuration exists
  stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.os_family }}/main.yaml"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: include_stats
  delegate_to: localhost
  become: false

- name: Running specific delegate setup
  include_tasks: "{{ ansible_facts.os_family }}/main.yaml"
  when: include_stats.stat.exists and include_stats.stat.isreg

- name: Common tasks
  import_tasks: shared_post/main.yaml
