#!/usr/bin/env ansible-playbook

- name: Adding bind
  hosts: "{{ host_override | default('dns') }}"
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - bind
  roles:
    - bind

#- name: Adding keepalived
#  hosts: "{{ host_override | default('dns') }}"
#  gather_facts: yes
#  become: yes
#  become_user: root
#  become_method: sudo
#  tags:
#    - keepalived
#  roles:
#    - keepalived
