---
# https://cbonte.github.io/haproxy-dconv/1.7/configuration.html
haproxy_defaults:
  global:
    daemon: true
    maxconn: 50000
    # https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#log
    log:
      address: /dev/log
      format: rfc3164
      facility: local0
      # any of [ emerg, alert, crit, err, warning, notice, info, debug ]
      level: info
    nbproc: "{{ (ansible_processor_vcpus | default(ansible_processor_cores | default(1))) / 2 | round(method='ceil') | int }}"
    pidfile: /run/haproxy.pid
    node: "{{ ansible_nodename }}"
    # Note: Should be later escaped for HTML
    description:

  defaults:
    timeout:
      check: 1s
      client: 1m
      connect: 1s
      http-keep-alive: 1m
      http-request: 30s
      queue: 1s
      server: 1m
      server-fin: 5s
      tarpit: 1m
      tunnel: 1h
  http:
    frontend:
      mode: http
      bind:
        - address: 0.0.0.0:80
          ssl: false
        - address: 0.0.0.0:443
          ssl: true
          crt: /etc/ssl/certs/haproxy.pem
          ssl-min-ver: TLSv1.2
      options:
        - forwardfor
      # http-request redirect scheme https unless { ssl_fc }
      https_redirect: true
    backend:
      balance: roundrobin
      servers: []
      # name:
      # address:
      # check: true
