---

- name: Installing NTP client
  dnf:
    name: chrony
    state: present

- name: Configuring NTP client
  template:
    src: chrony/chrony.conf.j2
    dest: /etc/chrony.conf
    mode: '644'
    owner: root
    group: root
  notify: restart chrony

- name: Enabling chrony daemon
  systemd:
    name: chronyd
    enabled: yes
    daemon_reload: yes

