---

- name: Giving rights to the folder
  file:
    path: "{{ bind_config_dir }}"
    state: directory
    owner: "{{ bind_group_name }}"
    mode: "{{ play_bind.primary | default(False) | ternary('750', '770') }}"

- name: Listing existing files
  find:
    paths:
      - "{{ bind_config_dir }}"
    file_type: file
  register: existing_configuration_files
  when: play_bind.primary

- name: Removing existing files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ existing_configuration_files.files }}"
  when: play_bind.primary

- name: Configuring zones.conf
  template:
    src: "zones.conf.j2"
    dest: "{{ bind_config_dir }}/zones.conf"
    owner: root
    group: "{{ bind_group_name }}"
    mode: '640'
    backup: no

- name: Configuring zones
  template:
    src: "db.zone.conf.j2"
    dest: "{{ bind_config_dir }}/db.{{ zone_def.zone }}"
    owner: root
    group: "{{ bind_group_name }}"
    mode: '640'
    backup: no
    validate: "named-checkzone {{ zone_def.zone }} %s"
  loop: "{{ ([play_host_zone_def] + play_bind.zones | default([])) }}"
  loop_control:
    loop_var: zone_def
    label: "{{ zone_def.zone }}"
  when: play_bind.primary

- name: Configuring reverse zones
  template:
    src: "db.zone-inv.conf.j2"
    dest: "{{ bind_config_dir }}/db.{{ zone_def.zone }}.inv"
    owner: root
    group: "{{ bind_group_name }}"
    mode: '640'
    backup: no
    validate: "named-checkzone {{ _reverse_zone_network }}.in-addr.arpa %s"
  loop: "{{ ([play_host_zone_def] + play_bind.zones | default([])) }}"
  loop_control:
    loop_var: zone_def
    label: "{{ zone_def.zone }}"
  vars:
    _reverse_zone_network: |-
      {{
        (
          (
            zone_def.network |
            ansible.netcommon.ipaddr('network')
          ).split('.') |
          list
        )[
          0
          :
          (
            (zone_def.network | ansible.netcommon.ipaddr('prefix') / 8) |
            round(method='ceil')                                        |
            int
          )
        ]         |
        reverse   |
        join('.')
      }}
  when:
    - play_bind.primary
    - zone_def.reverse
