---

- name: Updating service facts
  service_facts: {}

- name: Configuring SSH | Adding new SSH daemon port to the firewall
  ansible.posix.firewalld:
    port: '{{ sshd_port }}/tcp'
    state: enabled
    immediate: yes
    permanent: yes
  when:
    - "'firewalld.service' in ansible_facts['services']"
    - "ansible_facts['services']['firewalld.service']['state'] == 'running'"

- name: Configuring SSH | Notifying SELinux of the port change
  community.general.seport:
    ports: '{{ sshd_port }}'
    proto: tcp
    setype: ssh_port_t
    state: present
  when: "ansible_facts.selinux.status == 'enabled'"

- name: Regenerating SSH keys
  command:
    cmd: ssh-keygen -A
    creates: /etc/ssh/.ansible_keygen

- name: Configuring SSH | Configuring SSH daemon
  template:
    src: 'ssh/{{ ansible_facts.os_family }}/sshd_config.j2'
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
  notify: Restart sshd

