---

- name: Updating service facts
  service_facts: {}

- name: Creating the script directory
  file:
    path: /opt/scripts
    state: directory
    owner: root
    group: root

- name: Configuring virtual machines specifics | Adding a memory purge cron
  block:
    - name: Configuring virtual machines specifics | Adding a memory purge cron | Adding script
      copy:
        src: fs_cache_clean.sh
        dest: /opt/scripts/fs_cache_clean.sh
        remote_src: no
        force: yes
        backup: no
        mode: '755'
        owner: root
        group: root
        # The script must work
        validate: sh %s
    - name: Setting up cron
      cron:
        name: 'ansible_fs_cache_clean'
        cron_file: 'ansible_fs_cache_clean'
        job: "sh '/opt/scripts/fs_cache_clean.sh'"
        user: root
        state: present
        backup: no
        disabled: no
        minute: '*'
        hour: '*'
        day: '*'
        month: '*'
        weekday: '*'
  when:
    - "'crond.service' in ansible_facts['services']"
    - "'virtual' in group_names"

