---

- name: Creating groups and users
  import_tasks: 00_users.yaml

- name: Creating sudo roles
  import_tasks: 01_sudo.yaml

- name: Enabling selinux
  import_tasks: 02_selinux.yaml

- name: Enabling firewall
  include_tasks: 03_firewalld.yaml
  when: firewalld_enabled | default(True)

- name: Configuring fail2ban
  import_tasks: 04_fail2ban.yaml

- name: Configuring SSH daemon
  import_tasks: 05_sshd.yaml

- name: Configuring virtual machines
  import_tasks: 06_virutal_machines.yaml
