---

- name: Applying customizations
  import_tasks: 00_customization.yml

- name: Creating groups and users
  import_tasks: 01_users.yml

- name: Creating sudo roles
  import_tasks: 02_sudo.yml

- name: Configuring fail2ban
  import_tasks: 03_fail2ban.yml

- name: Configuring SSH daemon
  import_tasks: 04_sshd.yml

- name: Configuring virtual machines
  import_tasks: 05_virutal_machines.yml

