---

- name: Installing PostgreSQL
  dnf:
    name: "{{ packages.postgresql[ansible_facts.os_family] }}"
    state: present
    update_cache: yes
    disable_gpg_check: false
    validate_certs: yes
  throttle: 1

- name: Getting postgresql executables path
  block:
    - name: Getting postgresql executables path | Getting installed packages
      package_facts:
        manager: auto
        strategy: first
    - name: Getting postgresql executables path | Setting facts (1/3)
      set_fact:
        play_postgresql_version: |-
          {{-
            play_postgresql.force_version                                           |
            default(
              ansible_facts.packages[packages.postgresql[ansible_facts.os_family]]  |
              map(attribute='version')                                              |
              sort(reverse=True)                                                    |
              first                                                                 |
              regex_replace('^([0-9]+)\..*$', '\1')
            )
          -}}
    - name: Getting postgresql executables path | Setting facts (2/3)
      set_fact:
        play_postgresql_bindir: "/usr/pgsql-{{ play_postgresql_version }}/bin"
    - name: Getting postgresql executables path | Setting facts (3/3)
      set_fact:
        postgresql_pg_ctl_executable: "{{ play_postgresql_bindir }}/pg_ctl"
        postgresql_initdb_executable: "{{ play_postgresql_bindir }}/initdb"
        postgresql_repmgr_executable: "{{ play_postgresql_bindir }}/repmgr"

- name: Installing Repmgr
  dnf:
    name: "repmgr_{{ play_postgresql_version }}"
    state: present

- name: Configuring Systemd global services
  template:
    src: "postgresql/{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: '644'
  loop:
    - postgresql.service
    - postgresql@.service
  register: postgresql_global_services_config

- name: Reloading Systemd configuration
  systemd:
    daemon_reload: yes
  when: postgresql_global_services_config.changed

- name: Creating instances and configuring instances
  include_tasks: "{{ role_path }}/tasks/01_setup/postgresql/shared/00_cluster_tasks.yaml"
  loop: "{{ play_postgresql.instances.keys() }}"
  loop_control:
    loop_var: loop_postgresql_instance_definition_name

- name: Enabling global PostgreSQL service
  systemd:
    name: postgresql
    enabled: yes
