---

# Perform Systemd configuration

- name: Creating systemd service
  block:
    - name: Creating systemd service | Creating Systemd folder
      file:
        path: /etc/systemd/system/{{ play_instance_service_name }}.d
        state: directory
    - name: Creating systemd service | Creating service file
      template:
        src: postgresql/postgresql@-.service.j2
        dest: /etc/systemd/system/{{ play_instance_service_name }}.d/ansible-postgresql-setup.conf
        owner: root
        group: root
        mode: '644'

- name: Reloading Systemd and enabling service
  systemd:
    name: "{{ play_instance_service_name }}"
    enabled: yes
    daemon_reload: yes