---

# Configure a PostgreSQL cluster instance

- name: Loading shared variables
  include_tasks: "{{ role_path }}/tasks/01_setup/postgresql/shared/_variables.yaml"

- name: Applying configurations
  template:
    src: "postgresql/configuration/{{ item.src }}"
    dest: "{{ play_instance_pgdata_dir_fullpath }}/{{ item.dest }}"
    owner: postgres
    group: postgres
  loop:
    - src: pg_hba.conf.j2
      dest: configuration/pg_hba.conf
    - src: pg_ident.conf.j2
      dest: configuration/pg_ident.conf
    - src: postgresql.conf.j2
      dest: postgresql.conf
  register: instance_configurations

- name: Updating service facts
  service_facts: {}

- name: Restarting PostgreSQL in case of a change
  systemd:
    name: "{{ play_instance_service_name }}"
    state: restarted
  when: instance_configurations.changed