---

# Common shared variables

- name: Setting values (1/4)
  set_fact:
    play_postgresql_instance_definition: |-
      {{
        postgresql_instance_default |
        combine(
          play_postgresql.instances[loop_postgresql_instance_definition_name],
          recursive=True,
          list_merge='append',
        )
      }}

- name: Setting values (2/4)
  set_fact:
    play_instance_identifier: "{{ loop_postgresql_instance_definition_name | replace('/', '-') | replace(':', '-') }}"
    play_instance_pgdata_dir: "{{ loop_postgresql_instance_definition_name | replace('/', '-') | replace(':', '-') }}"

- name: Setting values (3/4)
  set_fact:
    play_instance_pgdata_dir_fullpath: "{{- play_postgresql.pgdata_base -}}/{{ play_postgresql_version }}/{{- play_instance_pgdata_dir -}}"
    play_instance_repmgr_dir_fullpath: "/etc/repmgr/{{ play_postgresql_version }}/{{- play_instance_pgdata_dir -}}"

- name: Setting values (4/4)
  set_fact:
    play_is_primary: |-
      {{-
        play_postgresql_instance_definition.is_primary              |
        default(inventory_hostname == (ansible_play_hosts | first)) |
        lower
      -}}
    play_instance_name: |-
      {%- if play_postgresql_instance_definition.force_version is defined -%}
        {{ play_postgresql_instance_definition.force_version -}}-{{- play_instance_identifier -}}
      {%- else -%}
        {{- play_instance_identifier -}}
      {%- endif -%}
    play_instance_pgdata_dir_fullpath_installation_lock_file: "{{- play_instance_pgdata_dir_fullpath -}}/{{ play_instance_pgdata_installation_lock_file_name }}"
    play_instance_service_name: "postgresql@{{- play_instance_identifier -}}.service"
    play_instance_repmgr_service_name: "postgresql-repmgr@{{- play_instance_identifier -}}.service"
    play_instance_repmgr_configuration_fullpath: "{{ play_instance_repmgr_dir_fullpath }}/repmgr.conf" 
