---
# vars file for postgresql

packages:
  repo_deb:
    Debian: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    Ubuntu: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
  repo_rpm:
    Debian:
    Ubuntu: 
    RedHat: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    CentOS: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    Fedora: "https://download.postgresql.org/pub/repos/yum/reporpms/F-{{ ansible_distribution_major_version }}-x86_64/pgdg-fedora-repo-latest.noarch.rpm"
  gpg_deb: 'https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc'
  gpg_rpm: 'https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG'
  postgresql:
    Debian: |-
      {%- if play_postgresql.force_version is defined -%}
        postgresql-{{ play_postgresql.force_version }}
      {%- else -%}
        postgresql
      {%- endif -%}
    RedHat: |-
      {%- if play_postgresql.force_version is defined -%}
        postgresql{{ play_postgresql.force_version }}-server
      {%- else -%}
        postgresql-server
      {%- endif -%}

play_software: "{{ play_postgresql.type | default('postgresql') | lower }}"
play_instance_pgdata_installation_lock_file_name: '.ansible_postgresql_installed'

postgresql_ignore_files:
  - postgresql.conf

postgresql_configuration_files:
  - pg_hba.conf
  - pg_ident.conf

postgresql_external_pid_file: |-
  {{
    play_postgresql.external_pid_file |
    default(
      '/run/postgresql/%s' | format(play_instance_identifier | replace('/', '-')),
      True
    )
  }}

postgresql_instance_default:
  listen_addresses: 0.0.0.0
  port: 5432
  max_connections: 100
  superuser_reserved_connections: 3
  #external_pid_file: ''
  unix_socket_directories:
    - /var/run/postgresql
    - /tmp
  tcp_keepalives_idle: 0
  tcp_keepalives_interval: 0
  tcp_keepalives_count: 0
  tcp_user_timeout: 0
  authentication_timeout_seconds: 60
  password_encryption: scram-sha-256
  db_user_namespace: false
  encoding: UTF8
  locale: 'en_US.UTF-8'
  # fr_FR.UTF-8
  text_search_configuration: 'pg_catalog.english'
  # pg_catalog.french
  timezone: UTC
  # Europe/Paris
  #log_timezone:
  databases: []
  users: []
  privileges: []

