---
# vars file for postgresql

postgresql_rhel_server_default_release: 14

postgresql_ignore_files:
  - postgresql.conf

postgresql_configuration_files:
  - pg_hba.conf
  - pg_ident.conf

packages:
  repo_deb:
    Debian: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    Ubuntu: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
  repo_rpm:
    Debian:
    Ubuntu: 
    RedHat: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    CentOS: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    Fedora: "https://download.postgresql.org/pub/repos/yum/reporpms/F-{{ ansible_distribution_major_version }}-x86_64/pgdg-fedora-repo-latest.noarch.rpm"
  gpg_deb: 'https://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc'
  gpg_rpm: 'https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG'
  postgresql:
    Debian: |-
      {%- if play_postgresql.force_version is defined -%}
        postgresql-{{ play_postgresql.force_version }}
      {%- else -%}
        postgresql
      {%- endif -%}
    RedHat: |-
      {%- if play_postgresql.force_version is defined -%}
        postgresql{{ play_postgresql.force_version }}-server
      {%- else -%}
        postgresql{{ postgresql_rhel_server_default_release }}-server
      {%- endif -%}

play_software: "{{ play_postgresql.type | default('postgresql') | lower }}"
play_instance_pgdata_installation_lock_file_name: '.ansible_postgresql_installed'

postgresql_external_pid_file: |-
  {{
    play_postgresql.external_pid_file |
    default(
      '/run/postgresql/%s' | format(play_instance_identifier | replace('/', '-')),
      True
    )
  }}

postgresql_instance_default:
  replication:
    enabled: False
    connect_timeout: 2
    # interface_address:
  listen_addresses: 0.0.0.0
  port: 5432
  max_connections: 100
  superuser_reserved_connections: 3
  #external_pid_file: ''
  unix_socket_directories:
    - /var/run/postgresql
    - /tmp
  tcp_keepalives_idle: 0
  tcp_keepalives_interval: 0
  tcp_keepalives_count: 0
  tcp_user_timeout: 0
  client_connection_check_interval: 0
  authentication_timeout_seconds: 60
  password_encryption: scram-sha-256
  db_user_namespace: false
  encoding: UTF8
  locale: 'en_US.UTF-8'
  # fr_FR.UTF-8
  text_search_configuration: 'pg_catalog.english'
  # pg_catalog.french
  datestyle: 'iso, mdy'
  timezone: UTC
  # Europe/Paris
  #log_timezone:
  databases: []
  users: []
  privileges: []

postgresql_repmgr:
  hba_entries: |-
    {%- set _hba_entries = [] -%}
    {#- Static entries -#}
    {{- _hba_entries.append({
        'type': 'local',
        'database': 'replication',
        'user': 'repmgr',
        'address': '',
        'method': 'trust'
      })
    -}}
    {{- _hba_entries.append({
        'type': 'host',
        'database': 'replication',
        'user': 'repmgr',
        'address': '127.0.0.1/32',
        'method': 'trust'
      })
    -}}
    {{- _hba_entries.append({
        'type': 'local',
        'database': 'repmgr',
        'user': 'repmgr',
        'address': '',
        'method': 'trust'
      })
    -}}
    {{- _hba_entries.append({
        'type': 'host',
        'database': 'repmgr',
        'user': 'repmgr',
        'address': '127.0.0.1/32',
        'method': 'trust'
      })
    -}}
    {#- Host entries -#}
    {%- for _host_name in ansible_play_hosts_all %}
    {%- set _loop_hostvars_postgresql_merged_values = 
      hostvars[_host_name]['postgresql'] | default({}) |
      combine(hostvars[_host_name]['postgresql_host'] | default({}), recursive=True, list_merge='append')
    -%}
    {%- set _host_address =
          (
            _loop_hostvars_postgresql_merged_values.replication.interface_address     |
            default(hostvars[_host_name]['ansible_facts']['default_ipv4']['address'])
          ) + '/' + (
            _loop_hostvars_postgresql_merged_values.replication.interface_address |
            default('0.0.0.0/32')                                                 |
            ansible.utils.ipaddr('prefix')                                        |
            string
          )
    -%}
    {%- if _loop_hostvars_postgresql_merged_values.type | default('postgresql') == 'postgresql' -%}
    {{- _hba_entries.append({
        'type': 'host',
        'database': 'replication',
        'user': 'repmgr',
        'address': _host_address,
        'method': 'trust'
      })
    -}}
    {{- _hba_entries.append({
        'type': 'host',
        'database': 'repmgr',
        'user': 'repmgr',
        'address': _host_address,
        'method': 'trust'
      })
    -}}
    {%- else -%}
    {{- _hba_entries.append({
        'type': 'host',
        'database': 'replication',
        'user': 'replication',
        'address': _host_address,
        'method': 'trust'
      })
    -}}
    {%- endif -%}
    {%- endfor -%}
    {{- _hba_entries -}}
  db_def:
    - name: repmgr
  user_def:
    - name: repmgr
      password: null
      database: repmgr
      role_attr_flags:
        - CREATEDB
        - CREATEROLE
        - SUPERUSER

