---

- name: Loading assertion messages
  include_vars:
    file: assertions.yaml

- name: Gathering system facts
  setup:
    gather_subset: all

- name: Gathering service facts
  service_facts: {}

- name: Facts must have been fetched
  assert:
    that:
      -  ansible_facts is defined
      - "{{ 'services' in ansible_facts }}"
      - "{{ 'os_family' in ansible_facts }}"
    fail_msg: '{{ assertion_messages.fact_fetch_error }}'

