---

- name: Checking for an existing PostgreSQL installation | Looking for a lock file
  stat:
    path: "{{ play_instance_pgdata_dir_fullpath_installation_lock_file }}"
    get_attributes: no
    get_checksum: no
    get_mime: no
    follow: no
  register: postgresql_installation_lock_stat_result

- name: Checking for an existing PostgreSQL installation | Registering variable
  set_fact:
    ansible_managed_installation_exists: "{{ postgresql_installation_lock_stat_result.stat.exists }}"
