---

# Common shared variables

- name: Setting values (1/5)
  set_fact:
    cacheable: yes
    ##
    play_postgresql_instance_definition: |-
      {{
        postgresql_instance_default |
        combine(
          play_postgresql.instances[loop_postgresql_instance_definition_name],
          recursive=True,
          list_merge='append',
        )
      }}

- name: Setting values (2/5)
  set_fact:
    cacheable: yes
    ##
    play_instance_identifier: "{{ loop_postgresql_instance_definition_name | replace('/', '-') | replace(':', '-') }}"
    play_instance_pgdata_dir: "{{ loop_postgresql_instance_definition_name | replace('/', '-') | replace(':', '-') }}"

- name: Setting values (3/5)
  set_fact:
    cacheable: yes
    ##
    play_instance_pgdata_dir_fullpath: "{{- play_postgresql.pgdata_base -}}/{{ play_postgresql_version }}/{{- play_instance_pgdata_dir -}}"
    play_instance_repmgr_dir_fullpath: "/etc/repmgr/{{ play_postgresql_version }}/{{- play_instance_pgdata_dir -}}"
    play_postgresql_external_pid_file: |-
      {{
        play_postgresql.external_pid_file |
        default(
          '/run/postgresql/%s' | format(play_instance_identifier | replace('/', '-')),
          True
        )
      }}
    play_postgresql_repmgr_external_pid_file: |-
      {{
        play_postgresql.external_pid_file |
        default(
          '/run/repmgr/%s' | format(play_instance_identifier | replace('/', '-')),
          True
        )
      }}

- name: Setting values (4/5)
  set_fact:
    cacheable: yes
    ##
    play_instance_is_primary: |-
      {{-
        play_postgresql_instance_definition.is_primary              |
        default(inventory_hostname == (ansible_play_hosts | first)) |
        lower
      -}}
    play_instance_name: |-
      {%- if play_postgresql_instance_definition.force_version is defined -%}
        {{ play_postgresql_instance_definition.force_version -}}-{{- play_instance_identifier -}}
      {%- else -%}
        {{- play_instance_identifier -}}
      {%- endif -%}
    play_instance_pgdata_dir_fullpath_installation_lock_file: "{{- play_instance_pgdata_dir_fullpath -}}/{{ play_instance_pgdata_installation_lock_file_name }}"
    play_instance_service_name: "postgresql@{{- play_instance_identifier -}}.service"
    play_instance_repmgr_service_name: "postgresql-repmgr@{{- play_instance_identifier -}}.service"
    play_instance_repmgr_configuration_fullpath: "{{ play_instance_repmgr_dir_fullpath }}/repmgr.conf"
    play_databases_create: |-
      {{
        play_postgresql_instance_definition.databases +
        (
          play_postgresql_instance_definition.replication.enabled |
          ternary(postgresql_repmgr.db_def, [])
        )
      }}
    play_users_create: |-
      {{
        play_postgresql_instance_definition.users +
        (
          play_postgresql_instance_definition.replication.enabled |
          ternary(postgresql_repmgr.user_def, [])
        )
      }}
    play_users_privileges: "{{ play_postgresql_instance_definition.privileges }}"

- name: Setting values (5/5)
  set_fact:
    play_instance_address: "{{ play_postgresql_instance_definition.replication.interface_address | default(ansible_facts.default_ipv4.address) }}"
    play_instance_listen_address: "{{- play_postgresql_instance_definition.listen_addresses | default(['0.0.0.0']) -}}"
    play_primary_host: |-
      {%- set _primary_hosts_list = [] -%}
      {%- for _play_host in ansible_play_hosts_all -%}
      {%- if play_software == 'postgresql' and hostvars[_play_host]['play_instance_is_primary'] | default(False) -%}
      {{- _primary_hosts_list.append(hostvars[_play_host]['ansible_facts']['default_ipv4']['address']) -}}
      {%- endif -%}
      {%- endfor -%}
      {{- _primary_hosts_list | first -}}
    play_barman_hosts_addresses: |-
      {%- set _barman_hosts_list = [] -%}
      {%- for _play_host in ansible_play_hosts_all -%}
      {%- if hostvars[_play_host]['play_software'] == 'barman' -%}
      {{- _barman_hosts_list.append(hostvars[_play_host]['ansible_facts']['default_ipv4']['address']) -}}
      {%- endif -%}
      {%- endfor -%}
      {{- _barman_hosts_list -}}
    play_db_extensions: |-
      {%- set db_extensions = [] -%}
      {%- for _database in play_databases_create -%}
      {%- for _extension_name in _database.extensions | default([]) -%}
      {{- db_extensions.append({
        'db': _database.name,
        'extension': _extension_name,
      }) -}}
      {%- endfor -%}
      {%- endfor -%}
      {{- db_extensions -}}

- name: Validating values
  assert:
    that: play_primary_host
