---
# defaults file for postgresql
postgresql_defaults:
  pgdata_base: |-
    {%- if ansible_facts.os_family == 'Debian' -%}
    /var/lib/postgresql
    {%- else -%}
    /var/lib/pgsql
    {%- endif -%}